/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'SendEmail': EventHandler<never, never>
    'SendEnhancedTitlesEmail': EventHandler<never, never>
    'AITitleInhenser': EventHandler<never, { topic: 'yt.enhanced.titles'; data: never } | { topic: 'yt.enhanced.titles.error'; data: never }>
    'FetchVideos': EventHandler<never, { topic: 'yt.fetched.videos'; data: never } | { topic: 'yt.fetched.videos.error'; data: never }>
    'ResolveChannel': EventHandler<never, { topic: 'yt.channel.resolved'; data: never } | { topic: 'yt.channel.error'; data: never }>
    'SubmitChannel': ApiRouteHandler<{ channel: string; email: string }, unknown, { topic: 'yt.submit'; data: never }>
  }
}